FLAGS = -Wall -Wextra -Werror -std=c++98

SRCS =	main.cpp\
		DiamondTrap.cpp\
		ScavTrap.cpp\
		FragTrap.cpp\
		ClapTrap.cpp\

all: $(SRCS)
	clang++ $(FLAGS) $(SRCS) -o DiamondTrap

clean:
	rm DiaomondTrap

re: